AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  EC2 Instance Starter

Globals:
  Function:
    Timeout: 3

Resources:
  EC2InstanceStarter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        StartEC2Instance:
          Type: Api
          Properties:
            Path: /start
            Method: post

Outputs:
  EC2InstanceStarterApi:
    Description: "API Gateway endpoint URL for Prod stage for EC2 Instance Starter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start/"
  EC2InstanceStarterIamRoleArn:
    Description: "Implicit IAM Role created for EC2 Instance Starter function"
    Value: !GetAtt EC2InstanceStarterRole.Arn
